const AnswerProvider = {
    answers: [
        // 谜语式答案
        { content: "月光下的影子知道答案", type: "riddle" },
        { content: "云中的倒影映照真相", type: "riddle" },
        { content: "沙漏里藏着时间的秘密", type: "riddle" },
        
        // 诗意隐喻
        { content: "蝴蝶振翅，引起千里之外的风暴", type: "metaphor" },
        { content: "沙漠中的第一滴雨，预示绿洲的方向", type: "metaphor" },
        { content: "黎明前的星光最为璀璨", type: "metaphor" },
        { content: "春雨润物细无声", type: "metaphor" },
        { content: "落叶归根，终有归处", type: "metaphor" },
        { content: "浮云散尽，明月依旧", type: "metaphor" },
        { content: "潮起潮落，自有时节", type: "metaphor" },
        
        // 哲理思考
        { content: "答案藏在时光的褶皱里", type: "philosophy" },
        { content: "真相如同空山的回声，需要你的呼唤", type: "philosophy" },
        { content: "命运的河流自有其方向", type: "philosophy" },
        { content: "生命如同一本正在书写的诗", type: "philosophy" },
        { content: "时间会给出最好的答案", type: "philosophy" },
        { content: "答案不在终点，而在路上", type: "philosophy" },
        
        // 暗示指引
        { content: "闭上眼睛，听从内心的声音", type: "guide" },
        { content: "答案就在你的脚下，抬头看天是找不到的", type: "guide" },
        { content: "月亮照亮你的影子，影子指向答案", type: "guide" },
        { content: "顺着风的方向，会找到归途", type: "guide" },
        
        // 玄学意境
        { content: "命运的书页正在翻转", type: "mystic" },
        { content: "星辰的轨迹已经显现", type: "mystic" },
        { content: "命运的丝线正在编织", type: "mystic" },
        { content: "时光的长河自有答案", type: "mystic" },
        
        // 自然启示
        { content: "春天总会再来", type: "nature" },
        { content: "风知道要去哪里", type: "nature" },
        { content: "花开不需要理由", type: "nature" },
        { content: "细雨润物无声", type: "nature" },
        
        // 简短神秘 (50条)
        { content: "月光下的影子知道答案", type: "riddle" },
        { content: "云中的倒影映照真相", type: "riddle" },
        { content: "沙漏里藏着时间的秘密", type: "riddle" },
        { content: "星辰轨迹", type: "short" },
        { content: "命运的齿轮在转动", type: "riddle" },
        { content: "听风的声音", type: "short" },
        { content: "静待花开", type: "short" },
        { content: "顺其自然", type: "short" },
        { content: "时机未到", type: "short" },
        { content: "水到渠成", type: "short" },
        { content: "一切随缘", type: "short" },
        { content: "且听风吟", type: "short" },
        { content: "未来可期", type: "short" },
        { content: "心有所向", type: "short" },
        { content: "随心而行", type: "short" },
        { content: "静观其变", type: "short" },
        { content: "万物有序", type: "short" },
        { content: "一念之间", type: "short" },
        { content: "心随境转", type: "short" },
        { content: "缘起缘灭", type: "short" },
        { content: "随波逐流", type: "short" },
        { content: "云卷云舒", type: "short" },
        { content: "月缺月圆", type: "short" },
        { content: "花开花落", type: "short" },
        { content: "潮起潮落", type: "short" },
        { content: "昼夜更替", type: "short" },
        { content: "四季轮回", type: "short" },
        { content: "星移斗转", type: "short" },
        { content: "物极必反", type: "short" },
        { content: "否极泰来", type: "short" },
        { content: "万物有灵", type: "short" },
        { content: "天机不可泄露", type: "short" },
        { content: "命中注定", type: "short" },
        { content: "缘分使然", type: "short" },
        { content: "一切皆有可能", type: "short" },
        { content: "未来已来", type: "short" },
        { content: "答案在风中", type: "short" },
        { content: "真相在云端", type: "short" },
        { content: "命运在眼前", type: "short" },
        { content: "机缘已至", type: "short" },
        { content: "时光会说话", type: "short" },
        { content: "星辰有预言", type: "short" },
        { content: "且行且思", type: "short" },
        { content: "心有灵犀", type: "short" },
        { content: "一念天堂", type: "short" },
        { content: "万物皆空", type: "short" },
        { content: "缘来缘去", type: "short" },
        { content: "随遇而安", type: "short" },
        { content: "一切皆有定数", type: "short" },
        { content: "命运自有安排", type: "short" },

        // 诗意隐喻 (50条)
        { content: "蝴蝶振翅，引起千里之外的风暴", type: "metaphor" },
        { content: "沙漠中的第一滴雨，预示绿洲的方向", type: "metaphor" },
        { content: "黎明前的星光最为璀璨", type: "metaphor" },
        { content: "春雨润物细无声", type: "metaphor" },
        { content: "落叶归根，终有归处", type: "metaphor" },
        { content: "浮云散尽，明月依旧", type: "metaphor" },
        { content: "潮起潮落，自有时节", type: "metaphor" },
        { content: "春风化雨，万物复苏", type: "metaphor" },
        { content: "星河滚烫，你是人间理想", type: "metaphor" },
        { content: "山川湖海，皆有归处", type: "metaphor" },
        { content: "晨露滋养，沉默的花开", type: "metaphor" },
        { content: "飞鸟投林，必有栖息", type: "metaphor" },
        { content: "星辰坠落，化作流萤", type: "metaphor" },
        { content: "风吹过竹林，留下清响", type: "metaphor" },
        { content: "雪融成泉，奔向大海", type: "metaphor" },
        { content: "荷花出淤泥而不染", type: "metaphor" },
        { content: "明月照古今，影落千家", type: "metaphor" },
        { content: "山间清泉，静静流淌", type: "metaphor" },
        { content: "云霞染天，昭示天机", type: "metaphor" },
        { content: "竹影横斜，写意人生", type: "metaphor" },
        { content: "梅傲寒冬，暗香浮动", type: "metaphor" },
        { content: "松柏经霜，愈发苍翠", type: "metaphor" },
        { content: "细雨织就春天的锦缎", type: "metaphor" },
        { content: "晚风吹皱一池春水", type: "metaphor" },
        { content: "山涧幽兰，暗香自来", type: "metaphor" },
        { content: "枯木逢春，焕发生机", type: "metaphor" },
        { content: "一叶知秋，万木染红", type: "metaphor" },
        { content: "星河璀璨，照亮归途", type: "metaphor" },
        { content: "海纳百川，有容乃大", type: "metaphor" },
        { content: "山高水长，自有定数", type: "metaphor" },
        { content: "云卷云舒，皆是自然", type: "metaphor" },
        { content: "春风十里，不如你", type: "metaphor" },
        { content: "明月千里，共此时", type: "metaphor" },
        { content: "落花有意，流水无情", type: "metaphor" },
        { content: "青山不老，为雪白头", type: "metaphor" },
        { content: "春去秋来，岁月如梭", type: "metaphor" },
        { content: "一花一世界，一叶一菩提", type: "metaphor" },
        { content: "山重水复疑无路，柳暗花明又一村", type: "metaphor" },
        { content: "风起于青萍之末", type: "metaphor" },
        { content: "水滴石穿，绳锯木断", type: "metaphor" },
        { content: "桃花潭水深千尺，不及汪伦送我情", type: "metaphor" },
        { content: "月上柳梢头，人约黄昏后", type: "metaphor" },
        { content: "江山如画，岁月如歌", type: "metaphor" },
        { content: "一树梨花压海棠", type: "metaphor" },
        { content: "莫听穿林打叶声，何妨吟啸且徐行", type: "metaphor" },
        { content: "小荷才露尖尖角，早有蜻蜓立上头", type: "metaphor" },
        { content: "山中相送罢，日暮掩柴扉", type: "metaphor" },
        { content: "采菊东篱下，悠然见南山", type: "metaphor" },

        // 哲理思考 (50条)
        { content: "答案藏在时光的褶皱里", type: "philosophy" },
        { content: "真相如同空山的回声，需要你的呼唤", type: "philosophy" },
        { content: "命运的河流自有其方向", type: "philosophy" },
        { content: "生命如同一本正在书写的诗", type: "philosophy" },
        { content: "时间会给出最好的答案", type: "philosophy" },
        { content: "答案不在终点，而在路上", type: "philosophy" },
        { content: "心有多远，路就有多远", type: "philosophy" },
        { content: "生命的意义在于寻找", type: "philosophy" },
        { content: "真理常常藏在矛盾中", type: "philosophy" },
        { content: "智者见智，仁者见仁", type: "philosophy" },
        { content: "万事万物，皆有其因", type: "philosophy" },
        { content: "看山是山，看水是水", type: "philosophy" },
        { content: "一切有为法，如梦幻泡影", type: "philosophy" },
        { content: "心若向阳，无谓春秋", type: "philosophy" },
        { content: "大道至简，大智若愚", type: "philosophy" },
        { content: "天地不仁，以万物为刍狗", type: "philosophy" },
        { content: "无问西东，但求本心", type: "philosophy" },
        { content: "人生如棋，落子无悔", type: "philosophy" },
        { content: "万般皆是命，半点不由人", type: "philosophy" },
        { content: "一切随缘，随缘不是放弃", type: "philosophy" },
        { content: "心有方向，脚下有路", type: "philosophy" },
        { content: "得之坦然，失之淡然", type: "philosophy" },
        { content: "无常即是常", type: "philosophy" },
        { content: "一切都是最好的安排", type: "philosophy" },
        { content: "心安即是归处", type: "philosophy" },
        { content: "随缘不变，不变随缘", type: "philosophy" },
        { content: "一切有为法，皆是虚妄", type: "philosophy" },
        { content: "因上努力，果上随缘", type: "philosophy" },
        { content: "心静自然明", type: "philosophy" },
        { content: "万法归一，一归何处", type: "philosophy" },
        { content: "有舍才有得", type: "philosophy" },
        { content: "无欲则刚", type: "philosophy" },
        { content: "知行合一", type: "philosophy" },
        { content: "物来顺应，未来不迎", type: "philosophy" },
        { content: "一切皆是修行", type: "philosophy" },
        { content: "心中有道，脚下有路", type: "philosophy" },
        { content: "万事皆空，一念不空", type: "philosophy" },
        { content: "心安理得，随遇而安", type: "philosophy" },
        { content: "一切现象，皆是幻相", type: "philosophy" },
        { content: "道法自然，人法地", type: "philosophy" },
        { content: "无心插柳柳成荫", type: "philosophy" },
        { content: "一切有为，终将化空", type: "philosophy" },
        { content: "随缘不逐，随遇而安", type: "philosophy" },
        { content: "心有所向，身有所往", type: "philosophy" },
        { content: "一切如梦，梦亦非梦", type: "philosophy" },
        { content: "道在日常", type: "philosophy" },
        { content: "一切皆缘，缘起缘灭", type: "philosophy" },
        { content: "心安即是家", type: "philosophy" },
        { content: "一切有时，万物有序", type: "philosophy" },
        { content: "随心而行，随性而为", type: "philosophy" },

        // 玄学意境 (50条)
        { content: "命运的书页正在翻转", type: "mystic" },
        { content: "星辰的轨迹已经显现", type: "mystic" },
        { content: "命运的丝线正在编织", type: "mystic" },
        { content: "时光的长河自有答案", type: "mystic" },
        { content: "命运的齿轮在悄然转动", type: "mystic" },
        { content: "冥冥之中自有天意", type: "mystic" },
        { content: "天机不可泄露", type: "mystic" },
        { content: "月影摇曳，暗示天机", type: "mystic" },
        { content: "星象已现，福祸可知", type: "mystic" },
        { content: "命运的天平正在倾斜", type: "mystic" },
        { content: "命运的罗盘在转动", type: "mystic" },
        { content: "时空的褶皱里藏着答案", type: "mystic" },
        { content: "命运的沙漏正在流淌", type: "mystic" },
        { content: "月相的变化预示方向", type: "mystic" },
        { content: "星辰的排列昭示天意", type: "mystic" },
        { content: "命运的画卷正在展开", type: "mystic" },
        { content: "时光的指针指向真相", type: "mystic" },
        { content: "命运的棋局已经布好", type: "mystic" },
        { content: "冥冥之中自有定数", type: "mystic" },
        { content: "玄机藏于无形之中", type: "mystic" },
        { content: "天意难测，人事难料", type: "mystic" },
        { content: "命运的帷幕正在拉开", type: "mystic" },
        { content: "时空的涟漪预示变化", type: "mystic" },
        { content: "命运的符号已经显现", type: "mystic" },
        { content: "玄机暗藏，天意难违", type: "mystic" },
        
        // 科学隐喻 (50条)
        { content: "熵增定律说：一切终将趋于平衡", type: "science" },
        { content: "量子纠缠：命运的羁绊无关距离", type: "science" },
        { content: "平行宇宙中，无数个可能同时存在", type: "science" },
        { content: "引力波动，牵动命运的涟漪", type: "science" },
        { content: "基因密码中写着生命的诗", type: "science" },
        { content: "暗物质般神秘，却无处不在", type: "science" },
        { content: "黑洞视界：答案在界限之外", type: "science" },
        { content: "光速不变，如同永恒的真理", type: "science" },
        { content: "DNA双螺旋：命运的纽带交织", type: "science" },
        { content: "量子叠加：所有可能同时存在", type: "science" },
        { content: "宇宙膨胀：万物皆在远离", type: "science" },
        { content: "相对论说：时间是柔软的", type: "science" },
        { content: "混沌理论：初始条件决定结局", type: "science" },
        { content: "能量守恒：得失之间必有平衡", type: "science" },
        { content: "量子隧穿：看似不可能，却必然发生", type: "science" },
        { content: "反物质：对立面成就完整", type: "science" },
        { content: "超弦理论：万物皆是振动", type: "science" },
        { content: "基本粒子：简单构成复杂", type: "science" },
        { content: "化学键：情感的作用力", type: "science" },
        { content: "光的波粒二象性：矛盾皆统一", type: "science" },
        { content: "热力学第二定律：时间的箭矢向前", type: "science" },
        { content: "薛定谔的猫：观测改变结果", type: "science" },
        { content: "分形几何：部分即是整体", type: "science" },
        { content: "测不准原理：命运总是模糊的", type: "science" },
        { content: "引力场：万物相互吸引", type: "science" },
        { content: "磁场线：看不见的指引", type: "science" },
        { content: "光谱：真相有多种色彩", type: "science" },
        { content: "电磁感应：变化产生力量", type: "science" },
    ],

    getRandomAnswer() {
        return this.answers[Math.floor(Math.random() * this.answers.length)];
    }
}; 
